import { useState } from 'react'
import api from '../services/api'
import { FileText, Download, Loader2, BookOpen, Lightbulb, Code, CheckCircle } from 'lucide-react'
import './AINotesGenerator.css'

const AINotesGenerator = ({ lessonId, lessonTitle }) => {
  const [loading, setLoading] = useState(false)
  const [notes, setNotes] = useState(null)
  const [activeTab, setActiveTab] = useState('overview')

  const generateNotes = async () => {
    setLoading(true)
    try {
      // In a real implementation, you'd get the transcript from the video
      // For now, we'll use the lesson title to generate notes
      const response = await api.post('/ai/notes', {
        lessonTitle,
        transcript: `Lesson about ${lessonTitle}. This is a placeholder transcript for demonstration.`,
        videoTitle: lessonTitle
      })
      setNotes(response.data.notes.notes)
    } catch (error) {
      console.error('Failed to generate notes:', error)
      alert('Failed to generate notes. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const downloadNotes = () => {
    if (!notes) return
    
    const content = `
${lessonTitle} - Study Notes

OVERVIEW
${notes.overview}

KEY CONCEPTS
${notes.keyConcepts?.map(c => `• ${c}`).join('\n')}

DEFINITIONS
${notes.definitions?.map(d => `${d.term}: ${d.definition}`).join('\n')}

SUMMARY
${notes.summary?.map(s => `• ${s}`).join('\n')}

Generated by LearnFlow AI
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${lessonTitle.replace(/\s+/g, '_')}_notes.txt`
    link.click()
    URL.revokeObjectURL(url)
  }

  if (!notes) {
    return (
      <div className="ai-notes-generator">
        <div className="notes-empty">
          <FileText size={48} className="notes-icon" />
          <h3>AI Study Notes</h3>
          <p>Generate comprehensive study notes for this lesson</p>
          <button
            onClick={generateNotes}
            disabled={loading}
            className="btn btn-primary"
          >
            {loading ? (
              <>
                <Loader2 className="spin" size={18} />
                Generating...
              </>
            ) : (
              <>
                <BookOpen size={18} />
                Generate Notes
              </>
            )}
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="ai-notes-generator">
      <div className="notes-header">
        <div className="notes-title">
          <FileText size={24} />
          <h3>AI Study Notes</h3>
        </div>
        <button onClick={downloadNotes} className="btn btn-outline btn-sm">
          <Download size={16} />
          Download
        </button>
      </div>

      <div className="notes-tabs">
        <button
          className={`tab ${activeTab === 'overview' ? 'active' : ''}`}
          onClick={() => setActiveTab('overview')}
        >
          <BookOpen size={16} />
          Overview
        </button>
        <button
          className={`tab ${activeTab === 'concepts' ? 'active' : ''}`}
          onClick={() => setActiveTab('concepts')}
        >
          <Lightbulb size={16} />
          Key Concepts
        </button>
        <button
          className={`tab ${activeTab === 'code' ? 'active' : ''}`}
          onClick={() => setActiveTab('code')}
        >
          <Code size={16} />
          Code Examples
        </button>
        <button
          className={`tab ${activeTab === 'summary' ? 'active' : ''}`}
          onClick={() => setActiveTab('summary')}
        >
          <CheckCircle size={16} />
          Summary
        </button>
      </div>

      <div className="notes-content">
        {activeTab === 'overview' && (
          <div className="tab-content">
            <h4>Overview</h4>
            <p>{notes.overview}</p>
          </div>
        )}

        {activeTab === 'concepts' && (
          <div className="tab-content">
            <h4>Key Concepts</h4>
            <ul className="concepts-list">
              {notes.keyConcepts?.map((concept, i) => (
                <li key={i}>{concept}</li>
              ))}
            </ul>
            
            <h4>Definitions</h4>
            <dl className="definitions-list">
              {notes.definitions?.map((def, i) => (
                <div key={i} className="definition-item">
                  <dt>{def.term}</dt>
                  <dd>{def.definition}</dd>
                </div>
              ))}
            </dl>
          </div>
        )}

        {activeTab === 'code' && (
          <div className="tab-content">
            <h4>Code Examples</h4>
            {notes.codeExamples?.map((example, i) => (
              <div key={i} className="code-example">
                <div className="code-header">{example.language}</div>
                <pre><code>{example.code}</code></pre>
              </div>
            ))}
          </div>
        )}

        {activeTab === 'summary' && (
          <div className="tab-content">
            <h4>Summary Points</h4>
            <ul className="summary-list">
              {notes.summary?.map((point, i) => (
                <li key={i}>{point}</li>
              ))}
            </ul>

            {notes.flashcards && (
              <>
                <h4>Flashcards</h4>
                <div className="flashcards">
                  {notes.flashcards.map((card, i) => (
                    <div key={i} className="flashcard">
                      <div className="flashcard-question">Q: {card.question}</div>
                      <div className="flashcard-answer">A: {card.answer}</div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

export default AINotesGenerator
